theme: jekyll-theme-modernist
relative_links:
  enabled: true
  collections: true
include:
  - polyester_simulation.html
  - Shuffling_reads.html
  - salmon_job_markdown.html
  - deseq_analysis_markdown.html
  - Flux_simulations.html
