#!/bin/bash
#SBATCH -N 1
#SBATCH -c 4
#SBATCH --mem=24g
#SBATCH --job-name shuffle-fasta

fullfile01=$1
fullfile02=$2

fasta01=`basename $fullfile01`
fasta02=`basename $fullfile02`

shuffled01=${fasta01%.fasta.gz}_shuffled.fasta
shuffled02=${fasta02%.fasta.gz}_shuffled.fasta

#######################
## go home
######################

mkdir -p ~/fastashuffle/
cd ~/fastashuffle/


######################
# unzip fasta files
#####################



echo "#### unzipp the 2 fasta files"
date
pigz -p 4 -dc ${fullfile01} | sed 's/ /_/g' >${fasta01%.gz}
pigz -p 4 -dc ${fullfile02} | sed 's/ /_/g' >${fasta02%.gz}
echo "### unzip completed"
date
echo "######## files in the folder are"
ls -l *



echo "#### shuffling the 2 fasta files"
date
cmd="paste ${fasta01%.gz} ${fasta02%.gz} | paste - - | shuf | awk '{print \$1 >\"$shuffled01\"; print \$3 >\"$shuffled01\"; print \$2 >\"$shuffled02\"; print \$4 >\"$shuffled02\"}'"
echo $cmd
eval $cmd
echo "#### shuffle completed"
date
echo "######## files in the folder are"
ls -l *


echo "#### compressing files again"
date
pigz -p 4 ${shuffled01}
pigz -p 4 ${shuffled02}
echo "#### compressing completed"
date
echo "######## files in the folder are"
ls -l *


echo "#### cleaning up"
